swagger: "2.0"
info: 
  version: "0.0.1"
  title: "aml"
  description: "A simple service to get cpuinfo as an example of using swagger-2.0 specification and codegen"
  termsOfService: "http://swagger.io/terms/"
  contact: 
    name: "Cloudmesh REST Service Example"
  license: 
    name: "Apache"
host: "localhost:8080"
basePath: "/cloudmesh/Boston"
schemes: 
  - "http"
consumes: 
  - "application/json"
produces: 
  - "application/json"
paths: 
  /predict:
    get: 
      description: "Returns cpu information of the hosting server"
      consumes:
      - "application/json"
      produces: 
        - "application/json"
      parameters:
      - in: "query"
        name: "data"
        type: "array"
        description: "Test"
        collectionFormat: "csv"
        items:
            type: "number"

              
      responses: 
        "200":
          description: "CPU info"
          schema: 
            $ref: "#/definitions/PREDICT"
definitions:
  PREDICT:
    type: "object"
    required: 
      - "model"
    properties: 
      model:
        type: "string"